# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-14 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_charity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='AboutUs',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charity',
            name='Website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
